FROM drupal:latest
RUN mkdir /var/www/html/sites/default/files  \
	&& chmod -R 777 /var/www/html/sites/default/files 
#VOLUME ["/var/www/html/profiles","var/www/html/modules","/var/www/html/themes","/var/www/html/sites/default"]
CMD []